server:
  port: 8082
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/activititest1
    username: postgres
    password: postgres
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
logging:
  level:
    com.len.mapper: DEBUG
    org.activiti.engine.impl.persistence.entity: trace    